# Generated by Django 2.1.7 on 2019-07-30 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('board_number', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=20, null=True)),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('contents', models.CharField(default='', max_length=1000, null=True)),
                ('date', models.DateTimeField(default='', null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='board_keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('keyword', models.CharField(default='', max_length=100)),
                ('word_date', models.DateTimeField(default='')),
                ('count', models.IntegerField(null=True)),
                ('pos_percent', models.FloatField(default=0.0, null=True)),
                ('neg_percent', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('comment_number', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lecture_evaluation',
            fields=[
                ('eval_number', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0, null=True)),
                ('assignment', models.CharField(default='', max_length=20, null=True)),
                ('team_project', models.CharField(default='', max_length=20, null=True)),
                ('credit', models.CharField(default='', max_length=20, null=True)),
                ('attendance', models.CharField(default='', max_length=20, null=True)),
                ('test', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lecture_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='major_keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='', max_length=20)),
                ('keyword', models.CharField(default='', max_length=100)),
                ('word_date', models.DateTimeField(default='')),
                ('count', models.IntegerField(null=True)),
                ('pos_percent', models.FloatField(default=0.0, null=True)),
                ('neg_percent', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='major_synonym',
            fields=[
                ('major', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('synonym', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='majors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='', max_length=20, null=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.colleges')),
            ],
        ),
        migrations.CreateModel(
            name='professor_keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='', max_length=20)),
                ('professor', models.CharField(default='', max_length=20)),
                ('keyword', models.CharField(default='', max_length=100)),
                ('word_date', models.DateTimeField(default='')),
                ('count', models.IntegerField(null=True)),
                ('pos_percent', models.FloatField(default=0.0, null=True)),
                ('neg_percent', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='search_major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='', max_length=20, null=True)),
                ('board_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.board')),
            ],
        ),
        migrations.CreateModel(
            name='smu_professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='', max_length=20, null=True)),
                ('professor', models.CharField(default='', max_length=20, null=True)),
                ('information', models.CharField(default='', max_length=100, null=True)),
                ('picture', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='smu_professor',
            unique_together={('major', 'professor')},
        ),
        migrations.AlterUniqueTogether(
            name='professor_keyword',
            unique_together={('major', 'professor', 'keyword', 'word_date')},
        ),
        migrations.AlterUniqueTogether(
            name='major_keyword',
            unique_together={('major', 'keyword', 'word_date')},
        ),
        migrations.AddField(
            model_name='lecture_time',
            name='professor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.smu_professor'),
        ),
        migrations.AddField(
            model_name='lecture_evaluation',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.lecture_time'),
        ),
        migrations.AddField(
            model_name='eval',
            name='comment_prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.lecture_evaluation'),
        ),
        migrations.AlterUniqueTogether(
            name='colleges',
            unique_together={('college',)},
        ),
        migrations.AlterUniqueTogether(
            name='board_keyword',
            unique_together={('code', 'keyword', 'word_date')},
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('code', 'title', 'contents')},
        ),
        migrations.AlterUniqueTogether(
            name='search_major',
            unique_together={('board_number', 'major')},
        ),
        migrations.AlterUniqueTogether(
            name='majors',
            unique_together={('college', 'major')},
        ),
        migrations.AlterUniqueTogether(
            name='lecture_time',
            unique_together={('lecture', 'professor')},
        ),
    ]
