# Generated by Django 2.1.7 on 2019-08-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
