# Generated by Django 2.2.4 on 2019-08-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_ratingprofessor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingprofessor',
            options={'ordering': ['-countEval', '-countKeyword']},
        ),
        migrations.CreateModel(
            name='ratingMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countBoard', models.IntegerField(null=True)),
                ('countKeyword', models.IntegerField(null=True)),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.majors')),
            ],
            options={
                'ordering': ['-countBoard', '-countKeyword'],
            },
        ),
    ]
