# Generated by Django 2.1.7 on 2019-08-04 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar',
        ),
    ]
