# Generated by Django 2.1.7 on 2019-08-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_remove_myuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
